### ISSUE TITLE
Handle spaces and tabs

### ISSUE THREAD

**Issue by ChristofferHolmesland** [ChristofferHolmesland/codetyper#13]
Suggestion:
- Convert every tab character to 4 spaces
- Let the user decide if they want to use tabs or spaces when they code. If the user presses tab then that can be converted to 4 spaces instead.

4 spaces will not work with every script, but it is a good starting point. A better solution would be to look at the code to find out how many spaces one tab should be.

**Comment by ACuteWoof** [comment]
> Convert every tab character to 4 spaces

So, I managed to do that and to allow the tab key to register, which I will add to my fork after cleaning up the code.

**Comment by ChristofferHolmesland** [comment]
Current status: tabs are converted to spaces, and both space and tab count as one space character. We should let people use tabs but we need a settings page first.
