### ISSUE TITLE
C# example cuts off mid snippet.

### ISSUE THREAD

**Issue by KoalaV2** [ChristofferHolmesland/codetyper#49]
![image](https://user-images.githubusercontent.com/27083886/126074748-97468802-640e-4681-903e-02fdf4c7d153.png)

The C# example ( May be other longer snippets too haven't tested that yet ) seems to randomly cut off mid snippet. On a screen with a 1680x1050 reselution using firefox.

**Comment by ChristofferHolmesland** [comment]
This is fixed now
